// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-features.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var FEATURES = [
  { id: "weather", name: "Weather Intelligence", description: "AI-powered weather predictions and farming recommendations." },
  { id: "soil-health", name: "Soil Health Assessment", description: "Comprehensive soil analysis and health recommendations." },
  { id: "disease-detection", name: "Plant Disease Detection", description: "AI-powered crop disease identification and treatment advice." },
  { id: "accounting", name: "Farm Accounting", description: "Financial management for income, expenses, and profitability." },
  { id: "market", name: "Market Analytics", description: "Real-time price predictions and market intelligence." },
  { id: "consultation", name: "Expert Consultation", description: "Connect with agricultural experts and community." }
];
var list_features_default = defineTool({
  name: "list_features",
  title: "List AgriSmart features",
  description: "List the AgriSmart app's available features with a short description of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FEATURES, null, 2) }],
    structuredContent: { features: FEATURES }
  })
});

// src/lib/mcp/tools/get-feature.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var get_feature_default = defineTool2({
  name: "get_feature",
  title: "Get AgriSmart feature",
  description: "Get details for a single AgriSmart feature by its id (e.g. 'weather', 'soil-health', 'disease-detection', 'accounting').",
  inputSchema: {
    id: z.string().min(1).describe("Feature id, such as 'weather' or 'disease-detection'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const feature = FEATURES.find((f) => f.id === id);
    if (!feature) {
      return {
        content: [{ type: "text", text: `No feature found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(feature, null, 2) }],
      structuredContent: { feature }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "agrismart-mcp",
  title: "AgriSmart MCP",
  version: "0.1.0",
  instructions: "Public read-only tools describing the AgriSmart agricultural management app. Use `list_features` to enumerate available capabilities and `get_feature` to fetch details for a specific one.",
  tools: [list_features_default, get_feature_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
